language: cpp
cache:
  - ccache
sudo: required
dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - g++
      - gcc
      - git
      - ccache

script:
  /bin/bash ./tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
