language: cpp
cache:
  - ccache
sudo: required
dist: trusty
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version 
  - g++ --version 

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - git
      - ccache

script:
  /bin/bash ./tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
