language: cpp
cache:
  - ccache
sudo: required
dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - g++-4.9.2
      - gcc-4.9.2
      - git
      - ccache

script:
  /bin/bash ./tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
