language: cpp
cache:
  - pip
  - ccache
  - yarn
  - npm
sudo: required
dist: trusty

os:
  - linux

env:
  - JOB=check_style
  - JOB=test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - git
      - python
      - python-pip
      - python2.7-dev
      - python-wheel
      - clang-format-3.8
      - ccache
      - npm
      - nodejs

before_install:
  - if [[ "$JOB" == "check_style" ]]; then sudo ln -s /usr/bin/clang-format-3.8 /usr/bin/clang-format; sudo pip install pre-commit flake8; fi

script:
  - gcc-5 --version
  - g++-5 --version
  - if [[ "$JOB" == "check_style" ]]; then .travis/check_style.sh; fi
  - if [[ "$JOB" == "test" ]]; then /bin/bash .travis/tests.sh; fi

notifications:
  email:
    on_success: change
    on_failure: always
